config/routes.rb
Remitwise::Application.routes.draw do

  get "users/show"

  get "invitations/accept"

  get "invitations/ignore"

  devise_for :users

  root :to => 'home#index'

  resources :remittances
  resources :connections

  resources :users, :only => [:show]

  resources :invitations, :only => [:index, :destroy] do
    member do
      get :accept
    end
  end

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  # GET /connections
  # GET /connections.json
  def index
    @receivers = current_user.receivers
    @senders = current_user.senders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:senders => @senders, :receivers => @receivers} }
    end
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
    @connection = Connection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @connection }
    end
  end

  # GET /connections/new
  # GET /connections/new.json
  def new
    @connection = Connection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @connection }
    end
  end

  # GET /connections/1/edit
  def edit
    @connection = Connection.find(params[:id])
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(params[:connection])

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render json: @connection, status: :created, location: @connection }
      else
        format.html { render action: "new" }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /connections/1
  # PUT /connections/1.json
  def update
    @connection = Connection.find(params[:id])

    respond_to do |format|
      if @connection.update_attributes(params[:connection])
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection = Connection.find(params[:id])
    @connection.destroy

    respond_to do |format|
      format.html { redirect_to connections_url }
      format.json { head :ok }
    end
  end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.haml
= form_for @connection do |f|
  -if @connection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@connection.errors.count, "error")} prohibited this connection from being saved:"
      %ul
        - @connection.errors.full_messages.each do |msg|
          %li= msg

  Sender id:
  = f.text_field :sender_id

  Receiver id:
  = f.text_field :receiver_id

  .actions
    = f.submit 'Save'

app/views/connections/edit.html.haml
%h1 Editing connection

= render 'form'

= link_to 'Show', @connection
\|
= link_to 'Back', connections_path

app/views/connections/index.html.haml
%h1 Listing connections

-if @receivers.any?
  %h3 People to whom you are sending money
  %ul  
    - @receivers.each do |user|
      %li= link_to user.email, user_path(user)

-if @senders.any?
  %h3 People to whom you are sending money
  %ul  
    - @senders.each do |user|
      %li= link_to user.email, user_path(user)

-if not (@senders.any? or @receivers.any?)
  .alert
    You are not connected to anyone.  Send someone a remittance to add them to your connections.

.alert.alert-error The link below should only be there for debugging, remove ASAP
= link_to 'New Connection', new_connection_path

app/views/connections/new.html.haml
%h1 New connection

= render 'form'

= link_to 'Back', connections_path

app/views/connections/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_connection_path(@connection)
\|
= link_to 'Back', connections_path