config/routes.rb
Remitwise::Application.routes.draw do

  get "users/show"

  get "invitations/accept"

  get "invitations/ignore"

  devise_for :users

  root :to => 'home#index'

  resources :remittances
  resources :connections

  resources :users, :only => [:show]

  resources :invitations, :only => [:index, :destroy] do
    member do
      get :accept
    end
  end

end

app/models/remittance.rb
class Remittance < ActiveRecord::Base

  belongs_to :user
  belongs_to :recipient, :class_name => "User"

  has_many :intended_uses

  attr_readonly :user_id, :recipient_email

end

app/controllers/remittances_controller.rb
class RemittancesController < ApplicationController
  # GET /remittances
  # GET /remittances.json
  def index
    @remittances_sent = current_user.remittances
    @remittances_received = current_user.received_remittances
    @remittance_months = @remittances_sent.group_by { |remittance| remittance.date.beginning_of_month }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remittances_sent }
    end
  end

  # GET /remittances/1
  # GET /remittances/1.json
  def show
    @remittance = Remittance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remittance }
    end
  end

  # GET /remittances/new
  # GET /remittances/new.json
  def new
    @remittance = Remittance.new

    @receivers = current_user.receivers

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remittance }
    end
  end

  # GET /remittances/1/edit
  def edit
    @remittance = Remittance.find(params[:id])
  end

  # POST /remittances
  # POST /remittances.json
  def create
    @remittance = Remittance.new(params[:remittance])

    if not params[:recipient_from_select].empty?
      user = User.find_by_id(params[:recipient_from_select])
      @remittance.recipient_email = user.email
    else
      email = params[:recipient_from_input]
      @remittance.recipient_email = email
      user = User.find_by_email(email)
    end

    @remittance.user = current_user

    if params[:intended_uses]
      params[:intended_uses].each do |use_hash|
        if not use_hash[:use].empty? and not use_hash[:money_amount].empty?
          use = IntendedUse.new use_hash
          @remittance.intended_uses.push use
        end
      end
    end

    if user and current_user.receivers.include? user
      @remittance.recipient_id = user.id
      respond_to do |format|
        if @remittance.save
          format.html { redirect_to @remittance, notice: 'Remittance was successfully created.' }
          format.json { render json: @remittance, status: :created, location: @remittance }
        else
          format.html { render action: "new" }
          format.json { render json: @remittance.errors, status: :unprocessable_entity }
        end
      end
    else
      Invitation.new({:user_id => current_user.id, :recipient_email => email}).save

      # TODO: send invitation email here

      respond_to do |format|
        if @remittance.save
          format.html { redirect_to @remittance, notice: "Remittance was successfully created; an invitation to join RemitWise was sent to #{email}" }
        end
      end
    end
  end

  # PUT /remittances/1
  # PUT /remittances/1.json
  def update
    @remittance = Remittance.find(params[:id])

    intended_uses_list = []

    params[:intended_uses].each do |use_hash|
      if not use_hash[:use].empty? and not use_hash[:money_amount].empty?
        use = IntendedUse.new use_hash
        indended_uses_list.push use
      end
    end

    # we use a temporary list instead of directly pushing so that items can be removed
    @remittance.intended_uses = intended_uses_list 

    respond_to do |format|
      if @remittance.update_attributes(params[:remittance])
        format.html { redirect_to @remittance, notice: 'Remittance was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @remittance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remittances/1
  # DELETE /remittances/1.json
  def destroy
    @remittance = Remittance.find(params[:id])
    @remittance.destroy

    respond_to do |format|
      format.html { redirect_to remittances_url }
      format.json { head :ok }
    end
  end
end

app/helpers/remittances_helper.rb
module RemittancesHelper
end

app/views/remittances/_form.html.haml
= form_for @remittance, :html => {:class => 'form-horizontal'} do |f|
  -if @remittance.errors.any?
    #error_explanation
      %h2= "#{pluralize(@remittance.errors.count, "error")} prohibited this remittance from being saved:"
      %ul
        - @remittance.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :recipient_email, 'To', :class => 'control-label'
    .controls
      -if @remittance.new_record?
        -if @receivers.any?
          = select_tag "recipient_from_select", options_from_collection_for_select(@receivers, "id", "email"), :prompt => "New Recipient"
        = text_field_tag "recipient_from_input", "", :class => 'input-xlarge', :placeholder => 'friend@gmail.com'
      -else
        = @remittance.recipient_email

  .control-group
    = f.label :amount, 'Amount', :class => 'control-label'
    .controls
      = f.text_field :amount, :class => 'input-xlarge', :placeholder => '100.00'

  .control-group
    = f.label :provider, 'Provider', :class => 'control-label'
    .controls
      = f.text_field :provider, :class => 'input-xlarge', :placeholder => 'Western Union'

  .control-group
    = f.label :message, 'Message', :class => 'control-label'
    .controls
      = f.text_area :message, :class => 'input-xlarge', :rows => 5, :columns => 20, :placeholder => 'Additional comment about remittance'

  .control-group
    = f.label :date, 'Date', :class => 'control-label'
    .controls
      = f.date_select :date

  .form-actions
    = f.submit 'Save Remittance', :class => ['btn','btn-primary']

  /   .field
  /     Intended uses

  /     = multiple_intended_use_form_section @remittance.intended_uses

app/views/remittances/_remittance.html.haml
.span6
  =remittance.amount
  to
  =remittance.recipient_email
  %ul
    %li
      This would be a great place for an intended use

app/views/remittances/edit.html.haml
%h1 Editing remittance

= render 'form'

= link_to 'Show', @remittance
\|
= link_to 'Back', remittances_path

app/views/remittances/index.html.haml
%h1 Remittances sent

%table
  %tr
    %th User
    %th Recipient
    %th Amount
    %th Provider
    %th Message
    %th Date
    %th
    %th
    %th

  - @remittances_sent.each do |remittance|
    %tr
      %td= remittance.user.email
      %td #{remittance.recipient_email} #{remittance.recipient ? "" : "(not a user yet)"}
      %td= remittance.amount
      %td= remittance.provider
      %td= remittance.message
      %td= remittance.date
      %td= link_to 'Show', remittance
      %td= link_to 'Edit', edit_remittance_path(remittance)
      %td= link_to 'Destroy', remittance, :confirm => 'Are you sure?', :method => :delete
%h1 Remittances received

%table
  %tr
    %th User
    %th Recipient
    %th Amount
    %th Provider
    %th Message
    %th Date
    %th
    %th
    %th

  - @remittances_received.each do |remittance|
    %tr
      %td= remittance.user.email
      %td #{remittance.recipient_email} #{remittance.recipient ? "" : "(not a user yet)"}
      %td= remittance.amount
      %td= remittance.provider
      %td= remittance.message
      %td= remittance.date
      %td= link_to 'Show', remittance
      %td= link_to 'Edit', edit_remittance_path(remittance)
      %td= link_to 'Destroy', remittance, :confirm => 'Are you sure?', :method => :delete

= link_to 'New Remittance', new_remittance_path

.row
  %h1.span6 My Remittances
  %h1.span6 How were they spent?
- @remittance_months.keys.sort.each do |month|
  .row
    %h2.span12= month.strftime("%B %Y")
  .row
    .span6
      - @remittance_months[month].each do |remittance|
        .row
          = render :partial => 'remittance', :locals => { :remittance => remittance }
    .span6
      Spent details for the month

app/views/remittances/new.html.haml
%h1 New remittance
%br

= render 'form'

= link_to 'Back', remittances_path

app/views/remittances/show.html.haml
%p#notice= notice

%p
  %b User:
  = @remittance.user.email
%p
  %b Recipient:
  = @remittance.recipient_email
%p
  %b Amount:
  = @remittance.amount
%p
  %b Provider:
  = @remittance.provider
%p
  %b Message:
  = @remittance.message
%p
  %b Date:
  = @remittance.date

%h3 Intended Uses

- @remittance.intended_uses.each do |use|
  %p #{use.use}: #{use.money_amount}

= link_to 'Edit', edit_remittance_path(@remittance)
\|
= link_to 'Back', remittances_path